(defwrk project-euler "problems currently being worked on"
  "~/projects/ProjectEuler/project.org"
  "~/projects/ProjectEuler/src/tools.clj"
  "~/projects/ProjectEuler/src/problem179.clj"
  "~/projects/ProjectEuler/src/problem191.clj"
  "~/projects/ProjectEuler/src/problem188.clj"
  "~/projects/ProjectEuler/src/problem282.clj"
)
(defwrk project-euler50 "stuck problems"
  "~/projects/ProjectEuler/src/tools.clj"
  "~/projects/ProjectEuler/src/problem015.clj"
  "~/projects/ProjectEuler/src/problem018.clj"
  "~/projects/ProjectEuler/src/problem023.clj"
  "~/projects/ProjectEuler/src/problem033.clj"
  "~/projects/ProjectEuler/src/problem032.clj"
  "~/projects/ProjectEuler/src/problem038.clj"
  "~/projects/ProjectEuler/src/problem043.clj"
  "~/projects/ProjectEuler/src/problem044.clj"
  "~/projects/ProjectEuler/src/problem046.clj"
  "~/projects/ProjectEuler/src/problem050.clj"
  "~/projects/ProjectEuler/src/problem067.clj"
  "~/projects/ProjectEuler/src/problem074.clj"
  "~/projects/ProjectEuler/src/problem075.clj"
)
