; Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

; 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
;    -        -          -

; Find the sum of all the even-valued terms in the sequence which do not exceed four million.

(ns p002
  (:use clojure.test))

(defn fibo []
  (map first (iterate (fn [[a b]] [b (+ a b)]) [0 1])))

(defn problem002 [n]
  (reduce + (filter #(even? %) (take-while #(< % n) (fibo)))))

(deftest test-problem002
  (is (= 44 (problem002 100))))

;; (time (problem002 4000000))
;; "Elapsed time: 2.032661 msecs"
;; 4613732
